
install:
  - ps: gitversion /l console /output buildserver

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_NuGetVersion)'

build_script:
  - cmd: dotnet build

test_script:
  - cmd: dotnet test .\ReportPortal.Shared.Tests\ReportPortal.Shared.Tests.csproj --no-build

after_test:
  - cmd: dotnet pack

artifacts:
  - path: '**\*.nupkg'